const POPULATE_MOVIE_LIST = "POPULATE_MOVIE_LIST";
const POPULATE_FAV_MOVIE_LIST = "POPULATE_FAV_MOVIE_LIST";
const ADD_MOVIE_TO_COLLECTION = "ADD_MOVIE_TO_COLLECTION";
const MOVIE_ADDED_TO_DB = "MOVIE_ADDED_TO_DB";
const DELETE_MOVIE_FROM_COLLECTION = "DELETE_MOVIE_FROM_COLLECTION";
const POPULATE_SEARCH_MOVIE_RESULTS = "POPULATE_SEARCH_MOVIE_RESULTS";
const LOAD_MORE_MOVIE = "LOAD_MORE_MOVIE";

export { 
	POPULATE_MOVIE_LIST,
	POPULATE_FAV_MOVIE_LIST,
	ADD_MOVIE_TO_COLLECTION,
	MOVIE_ADDED_TO_DB,
	DELETE_MOVIE_FROM_COLLECTION,
	POPULATE_SEARCH_MOVIE_RESULTS,
	LOAD_MORE_MOVIE
};
